### ISSUE TITLE
[BUG] activation module with redirect set to true fails if API returns a 302 (possibly only HTTPS)

### ISSUE THREAD

**Issue by hb9hnt** [Checkmk/ansible-collection-checkmk.general#527] opened 2024-01-23 06:07 UTC
**Describe the bug**
The activation handler in the Agent role specifies `redirect: true` as can be seen here:

https://github.com/Checkmk/ansible-collection-checkmk.general/blob/c32c2cca180d957bf9774f002573bdda28dd3c68/roles/agent/handlers/main.yml#L10

This leads to an error if the API returns a 302. The `fetch_url` from `ansible_utils.url` (which internally users `requests`) seems to try to follow the redirect which does not work in our case where we terminate HTTPS on the outer Apache. From the log of the outer Apache it seems that the `302` redirects to plain HTTP which ends in a `400` error:

```
10.1.1.70 - - [22/Jan/2024:15:05:15 +0000] "POST //monitoring/check_mk/api/1.0/domain-types/activation_run/actions/activate-changes/invoke HTTP/1.1" 302 8485 "-" "ansible-httpget"
10.1.1.70 - - [22/Jan/2024:15:05:15 +0000] "GET / HTTP/1.0" 400 631 "-" "-"
```

In the Ansible output we get a rather cryptic error because it only reports the final message of the `400` status

```
400 - Bad request: Parameter or validation failure Details: b'<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You\\'re speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
<hr>
<address>Apache/2.4.52 (Ubuntu) Server at example.com Port 443</address>
</body></html>
```

**Component Name**

The following components are affected:
* activation handler in the agent role
* the activation Ansible plugin

**Ansible Version**
We use AWX exectuion environments running Ansible Core 2.15.

**Checkmk Version and Edition**
```console
2.2.0p11 Cloud Edition
```

**Collection Version**
This is not easily obtained from the AWX execution environment. I don't think it's relevant here. We use the checkmk Ansible collection `4.1.0`

**To Reproduce**
1. Create a setup where you terminate SSL on the outer Apache as described here https://docs.checkmk.com/latest/en/omd_https.html
2. Use the Agent role to make a lot of changes that take long to activate. This is the hardest part to reliably reproduce. Often changes take short to activate and the API will return a `200` status. You have to make sure you activate enough changes on enough different sites for the API to return a `302`.
3. Make sure the Activation handler is executed.
4. See error above.

**Expected behavior**
Honestly, I'm not sure what the best correct behavior would be here. As I see it there are several things to consider:

* That the `302` of the API redirects to HTTP rather than HTTPS in an HTTPS environment is a bug in the API IMHO.
* I don't think the activation Ansible module should even offer the asynchron `redirect: true` option. It is not clear to me how Ansible should handle the `302` status. If you want async functionality in the activation module you can achieve the same with the built-in Ansible `async` tool.

**Actual behavior**
Already described above. in the case of a `302` from the API as documented if you use the `redirect: true` option, Ansible gives you the mentioned error.

**Minimum reproduction example**
Create a lot of changes on different sites and do an activation with `redirect: true`
```yaml
- name: "Activate Changes."
  checkmk.general.activation:
    server_url: "https://my.checkmk.instance/"
    site: "my_site"
    automation_user: "automation"
    automation_secret: "12345"
    force_foreign_changes: "true"
    # This is the crucial option:
    redirect: 'true'
```

**Additional context**
If you agree that the `checkmk.general.activation` should not offer the `redirect: true` option I'd be willing to volunteer a PR removing it everywhere.

Thanks

Beni

**Comment by Max-checkmk** [comment] 2024-01-23 08:16
Hi Beni,

thank you very much for this very well described problem.
I will look into this. As you already wrote the steps to reproduce this need some work, so please don't expect a solution within a few days.

I would suggest not to remove this option, but to handle the redirect properly.
If it's a bug in the API, we have to fix it there anyway.

KR,
Max

**Comment by Max-checkmk** [comment] 2024-02-07 09:12
Hi Beni,

i know that your example is about the activation endpoint, but it looks like the issue we already have with #414 is the same. Can you confirm this?

KR,
Max

**Comment by hb9hnt** [comment] 2024-02-07 13:36
Hey @Max-checkmk 

I do agree that the cause of the issue is the same: calling an API endpoint which possibly returns a 302 to a background job. However I don't agree that the two issues are the same, because the discovery endpoint `domain-types/service_discovery_run/actions/start/invoke` doesn't give you the option to set `redirect: false` and make the request synchronous. 

IMHO solving this issue is a lot easier than fixing #441 and the resolution that makes sense for #441 might not applicable for the activation endpoint described here.

However, you know the inner workings of Checkmk way better than I do. If you already see a solution that's applicable to both endpoints I'm interested in how you'd solve it.

--Beni

**Comment by Max-checkmk** [comment] 2024-03-07 09:16
Hi Beni,

i just had a customer ticket where we had the exact same problem.
The API answers with the same protocol in which the request came in.
In this case the system apache wasn't configured to forward the https to the site apache.

Could you please check if your system apache is configured like described here?
https://docs.checkmk.com/latest/en/omd_https.html?lquery=apache#httpsredirect

It's about those lines:
`<IfModule headers_module>
    RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
    RequestHeader set X-Forwarded-SSL expr=%{HTTPS}
</IfModule>`

KR,
Max

**Comment by hb9hnt** [comment] 2024-03-07 11:17
Hey Max

I can confirm that this header was missing from my config. I added the header. At the moment I don't have the opportunity to test this, but I think we can assume that this issue doesn't need fixind.

Thank you and regards

Beni

**Comment by robin-checkmk** [comment] 2024-03-07 13:28
Thanks for the update guys! :pray: 

I will close this issue then for now, if the issue remains, feel free to re-open it @hb9hnt. :v:

**Closed by robin-checkmk** 2024-03-07 13:28 UTC
Labels: bug
