### ISSUE TITLE
[FEED] Consider using 'throttle' to avoid API errors when using large inventories.

### ISSUE THREAD

**Issue by andreiciulinaru** [Checkmk/ansible-collection-checkmk.general#328] opened 2023-05-03 10:48 UTC
While running the Ansible [agent role](https://github.com/Checkmk/ansible-collection-tribe29.checkmk/tree/main/roles/agent/tasks) on an inventory with multiple hosts, I often occur API errors or timeouts when multiple hosts try to register for TLS or to Activate changes at the same time.

I believe that CheckMK API does not properly handle multiple hosts registering at the same time.

**Component**

```
name: "Register Agent for TLS."
  become: true
  ansible.builtin.shell: |
    cmk-agent-ctl register -H {{ checkmk_agent_host_name }} \
    -s {{ checkmk_agent_registration_server }} -i {{ checkmk_agent_registration_site }} \
    -U {{ checkmk_agent_user }} -P {{ checkmk_agent_auth }} --trust-cert
```
**Output**
```
changed: [host01 ]
changed: [host02 ]
changed: [host03 ]
changed: [host04 ]
changed: [host05 ]
fatal: [host06 -> localhost]: FAILED! => {"changed": false, "http_code": -1, "msg": "Error calling API. HTTP Return Code is -1 Details: Connection failure: The read operation timed out"}
fatal: [host07 -> localhost]: FAILED! => {"changed": false, "http_code": -1, "msg": "Error calling API. HTTP Return Code is -1 Details: Connection failure: The read operation timed out"}
```

**Ansible Version**

```console
ansible [core 2.14.5]

```

**Collection Version**

```console
tribe29.checkmk   0.16.2

```

**Suggestion**
Consider using the [throttle](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_strategies.html#restricting-execution-with-throttle) mechanism to only execute API calls one by one.

Example: 
```
- name: "Register Agent for TLS."
  become: true
  ansible.builtin.shell: |
    cmk-agent-ctl register -H {{ checkmk_agent_host_name }} \
    -s {{ checkmk_agent_registration_server }} -i {{ checkmk_agent_registration_site }} \
    -U {{ checkmk_agent_user }} -P {{ checkmk_agent_auth }} --trust-cert
  register: checkmk_agent_tls_state
  throttle: 1
```

**Comment by robin-checkmk** [comment] 2023-05-08 08:39
Hi @andreiciulinaru and thanks for reporting this.
I am not yet confident, if I want to throttle this task as harshly as you suggest. I need more data.
Can you reproduce this issue every time? Do you have some statistical data on how many hosts work, before you get the timeouts?

**Comment by andreiciulinaru** [comment] 2023-05-12 09:30
Hi @robin-checkmk 
I can reproduce errors each time, but for the last two attempts, it failed when discovering new services on hosts.
Running the playbook on 7 hosts each time, the first 5 succeeded and the latter fail. The same behaviour as initially described.


TASK [check_mk : Discover services and labels on host.]
changed: [checkmk01test -> localhost]
changed: [checkmk02test -> localhost]
changed: [checkmk03test -> localhost]
changed: [checkmk04test -> localhost]
changed: [checkmk05test -> localhost]
`
fatal: [checkmk06test -> localhost]: FAILED! => {
    "changed": false,
    "http_code": -1,
    "invocation": {
        "module_args": {
            "automation_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "automation_user": "user",
            "host_name": "checkmk06test",
            "server_url": "https://cmk.local:443/",
            "site": "HQ",
            "state": "fix_all",
            "validate_certs": false
        }
    },
    "msg": "Error calling API. HTTP Return Code is -1 Details: Connection failure: The read operation timed out"
}
`

`
fatal: [checkmk07test -> localhost]: FAILED! => {
    "changed": false,
    "http_code": -1,
    "invocation": {
        "module_args": {
            "automation_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "automation_user": "user",
            "host_name": "checkmk07test",
            "server_url": "https://cmk.local:443/",
            "site": "HQ",
            "state": "fix_all",
            "validate_certs": false
        }
    },
    "msg": "Error calling API. HTTP Return Code is -1 Details: Connection failure: The read operation timed out"
}
`

CheckMK apache logs:
I noticed the first 5 POST requests are grouped and sent at the same time.
```
[12/May/2023:08:39:38 +0000] "POST /check_mk/api/1.0/objects/host/checkmk02test/actions/discover_services/invoke HTTP/1.1" 200 26337 "-" "ansible-httpget"
[12/May/2023:08:39:38 +0000] "POST /check_mk/api/1.0/objects/host/checkmk01test/actions/discover_services/invoke HTTP/1.1" 200 26337 "-" "ansible-httpget"
[12/May/2023:08:39:38 +0000] "POST /check_mk/api/1.0/objects/host/checkmk03test/actions/discover_services/invoke HTTP/1.1" 200 26337 "-" "ansible-httpget"
[12/May/2023:08:39:38 +0000] "POST /check_mk/api/1.0/objects/host/checkmk05test/actions/discover_services/invoke HTTP/1.1" 200 26337 "-" "ansible-httpget"
[12/May/2023:08:39:38 +0000] "POST /check_mk/api/1.0/objects/host/checkmk04test/actions/discover_services/invoke HTTP/1.1" 200 26337 "-" "ansible-httpget"
[12/May/2023:08:39:44 +0000] "POST /check_mk/api/1.0/objects/host/checkmk06test/actions/discover_services/invoke HTTP/1.1" 200 26337 "-" "ansible-httpget"
[12/May/2023:08:39:49 +0000] "POST /check_mk/api/1.0/objects/host/checkmk07test/actions/discover_services/invoke HTTP/1.1" 200 26337 "-" "ansible-httpget"
```


I further tried to increase the default timeout period from 60s to 120s (in ansible-collection-tribe29.checkmk/plugins/modules/discovery.py)  with no success.

```
    api_endpoint = (
        "/objects/host/"
        + module.params.get("host_name")
        + "/actions/discover_services/invoke"
    )
    url = base_url + api_endpoint
    response, info = fetch_url(
        module, url, module.jsonify(params), headers=headers, method="POST", timeout=120
    )
```

This issue seems to be somewhat related https://forum.checkmk.com/t/rest-api-problem-with-service-discovery/31724
I also ran the tests on check_mk 2.1.0p20

Will update you if I find new things.
Thank you!

**Comment by robin-checkmk** [comment] 2023-05-12 10:05
Hi @andreiciulinaru and thanks for the extensive feedback, I appreciate it!
The batching of requests makes sense, as Ansible has a default batch size of 5.
It looks like the problem is actually in the API and not in the collection, so all we could do is a workaround.
But we are looking into this and will also update as soon as we find something.

**Comment by robin-checkmk** [comment] 2023-06-30 14:48
@andreiciulinaru there was a fix implemented in #369 which is available in `2.3.0` of `checkmk.general`.
Can you try that version and report back, if that improved your situation? Thanks!

**Comment by andreiciulinaru** [comment] 2023-07-07 09:22
Hi @robin-checkmk ,
I installed the new collection:
checkmk.general   2.3.0

I updated the playbook by renaming modules (e.g. from `tribe29.checkmk.discovery` to `checkmk.general.discovery`)

```
- name: "Discover services and labels on host."  
  become: false. 
  checkmk.general.discovery:    
    server_url: "{{ checkmk_agent_protocol }}://{{ checkmk_agent_server }}:{{ checkmk_agent_port }}/"
    site: "{{ checkmk_agent_site }}"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    automation_user: "{{ checkmk_agent_user }}"
    automation_secret: "{{ checkmk_agent_auth }}"
    host_name: "{{ checkmk_agent_host_name }}"
    state: "fix_all" 
  delegate_to: "{{ checkmk_agent_delegate_api_calls }}"
  when: checkmk_agent_discover | bool
  notify: "activate changes"

```

Now I'm getting API timeouts when discovering services on a host. Am I missing something?
```
TASK [check_mk : Discover services and labels on host.] ***************************************************************************************************
fatal: [ansibletest -> localhost]: FAILED! => {"changed": false, "msg": "-1 - Error calling API Details: Connection failure: The read operation timed out"}
```

All the other tasks succeed.

**Comment by robin-checkmk** [comment] 2023-07-27 08:17
> Now I'm getting API timeouts when discovering services on a host. Am I missing something?

This should be fixed with #384.

There are again some changes in the pipeline for the `2.4.0` release, which might solve the initial issue.
However, the more I think about this, the less I want to implement a throttling in the role.
Would you be fine, if we added a remark in the README, that it might be necessary to throttle the discovery or run it as a bulk job after the role ran, instead of having the role do it?

**Comment by andreiciulinaru** [comment] 2023-08-10 08:53
Hi Robin,
I upgraded to checkmk.general 2.4.1, while still using the API on 2.1.0p20-cee.

```
TASK [check_mk : Discover services and labels on host.] ********************************************************************************************************************************************************
changed: [cmktest1 -> localhost]
changed: [cmktest3 -> localhost]
fatal: [cmktest2 -> localhost]: FAILED! => {"changed": false, "msg": "-1 - Error calling API Details: Connection failure: The read operation timed out"}
fatal: [cmktest5 -> localhost]: FAILED! => {"changed": false, "msg": "-1 - Error calling API Details: Connection failure: The read operation timed out"}
fatal: [cmktest4 -> localhost]: FAILED! => {"changed": false, "msg": "-1 - Error calling API Details: Connection failure: The read operation timed out"}
changed: [cmktest6 -> localhost]
```

However, I am completely fine with throttling this task one by one, which works perfectly for me. Until I upgrade the CheckMk core, I will keep it this way.
So, yes, I believe adding a hint in README is a good idea. Will keep you updated if I find anything new.

**Comment by robin-checkmk** [comment] 2023-08-10 09:53
In #403 we actually enabled throttling in the agent role. The release (#405) will be done before end of the week. I am looking forward to your feedback on the changes.

**Closed** 2023-08-11 09:48 UTC
Labels: feedback, role:agent, release:3.0.0
