### ISSUE TITLE
[BUG] update_attribute on folder always results in 'changed'

### ISSUE THREAD

**Issue by Dennis-Q** [Checkmk/ansible-collection-checkmk.general#642] opened 2024-07-22 15:21 UTC
**Describe the bug**
update_attribute to change contact groups always causes a 'changed' (and actual rule to activate) even though the value already is configured like this. 

**Component Name**
Component Name: folder (possibly more)

**Ansible Version**

```console
$ ansible --version
ansible [core 2.15.12]
  config file = /home/<user>/repos/ansible-checkmk/ansible.cfg
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<user>/venvs/ansible-checkmk/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/<user>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<user>/venvs/ansible-checkmk/bin/ansible
  python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/home/<user>/venvs/ansible-checkmk/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Checkmk Version and Edition**

```console
2.2.0p28 cee
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection                               Version
---------------------------------------- -------
ansible.posix                            1.5.4  
ansible.utils                            5.0.0  
brocade.fos                              1.3.3  
checkmk.general                          5.1.0 
```

**To Reproduce**
1. Create a folder in Main called 'eu'
2. User folder module to update contact groups using update_attributes section:, e.g.
```
- name: "Update folder contactgroups for main and site specific folders"
  checkmk.general.folder:
    server_url: "{{ master_site_baseurl }}"
    site: "{{ master_site }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    path: "{{ item.path.lower() }}"
    name: "{{ item.name }}"
    update_attributes:
      contactgroups:
        groups: "{{ item.contactgroups }}"
        use: "{{ item.contact | default('false') }}" 
        use_for_services: "{{ item.contact | default('false') }}"
        recurse_use: "{{ item.contact | default('false') }}"
        recurse_perms: "{{ item.recurse_perms | default('false') }}"
    state: "{{ item.state | default('present') }}"
  delegate_to: localhost
  throttle: 1
  loop:
    - { name: "EU", path: "/eu", contactgroups:  [ "g_cg_windowsengineers", "g_cg_linuxengineers", "g_cg_vmwareengineers", "g_cg_hypervengineers", "g_cg_networkengineers", "g_cg_aixengineers", "g_cg_hardwareengineers", "g_cg_kubernetesengineers", "g_cg_storageengineers" ] }
```
3. Run the playbook with above task
4. (optional: activate changes)
5. Run the playbook with above task... It will keep saying 'Changed'

**Expected behavior**
In general, Ansible (modules) look at the end result and only execute changes when it needs to. In this case, after the second run, it should not change anything but state 'OK' instead.

**Actual behavior**
Everytime the playbooks runs, the folder is updated and ansible states 'changed'. Not just in the first run, but on any run after the first run as well.

**Comment by robin-checkmk** [comment] 2024-07-24 07:09
Hi @Dennis-Q and thanks for reporting this!
To clarify:
There is a change triggered in Checkmk, but the values and configuration did not change effectively.
So the issue here is no faulty configuration, but an unnecessary change in Checkmk, triggering the need to activate changes.
Is that correct?

**Comment by Dennis-Q** [comment] 2024-07-24 07:36
Hi @robin-checkmk ,

yes, the first time it does change things (to what it is supposed to be), but the second time (and all the runs after), there's no change indeed in configuration, but Ansible does state 'changed' and there are pending changing in checkmk that indeed need activation of changes.

**Comment by msekania** [comment] 2024-07-24 08:26
Hi @robin-checkmk , Hi @Dennis-Q 

the problem might be in how the default values are handled.  Some of them are **returned** as `false`, others are **assumed** as `false` but not returned. Similar to those problems in the rules module.

@Dennis-Q, a quick fix might be to avoid explicitly setting `false`, or trying out which are required and which are not.

I'll take a look at the folder module later this week to see how to improve it.

**Comment by Dennis-Q** [comment] 2024-07-24 18:07
@msekania @robin-checkmk 
Yes, you are correct, I have changed the default('false') to default(omit) and now all is good.

Apart from the fact that I think you should be able to explicitly define the value you want (defaults might change), it also doesn't seem to work with non-default values (true in this case)..

The new play I tried:

```
- name: "Update folder contactgroups for main and site specific folders"
  checkmk.general.folder:
    server_url: "{{ master_site_baseurl }}"
    site: "{{ master_site }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    path: "{{ item.path.lower() }}"
    name: "{{ item.name }}"
    update_attributes:
      contactgroups:
        groups: "{{ item.contactgroups }}"
        use: "{{ item.contact | default(omit) }}" 
        use_for_services: "{{ item.contact | default(omit) }}"
        recurse_use: "{{ item.contact | default(omit) }}"
        recurse_perms: "{{ item.recurse_perms | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  delegate_to: localhost
  throttle: 1
  loop:
    - { name: "EU", path: "/eu", contactgroups:  [ "g_cg_windowsengineers", "g_cg_linuxengineers", "g_cg_vmwareengineers", "g_cg_hypervengineers", "g_cg_networkengineers", "g_cg_aixengineers", "g_cg_hardwareengineers", "g_cg_kubernetesengineers", "g_cg_storageengineers" ]  }
    - { name: "EU2", path: "/eu2", contactgroups:  [ "g_cg_windowsengineers", "g_cg_linuxengineers", "g_cg_vmwareengineers", "g_cg_hypervengineers", "g_cg_networkengineers", "g_cg_aixengineers", "g_cg_hardwareengineers", "g_cg_kubernetesengineers", "g_cg_storageengineers" ], contact: 'true'  }
```

With the above example, the first one shows OK (since item.contact is not defined and all the values are omitted). But the second item of the loop always says 'changed'. Since the default is 'false' and we configure it to 'true' here, I would have expected that with the second run it shows 'OK' too (since it does differ from the default) if your theory is correct.

So it's not just the default values, but it seems to have to do with the additional settings you can configure in the 'contactgroups' section (use, use_for_services, recurse_use and recurse_perms) that aren't verified/checked correctly if used (or something like that..)

Thanks for checking it later this week! :)

**Comment by msekania** [comment] 2024-07-25 12:00
@Dennis-Q,

interesting...
Actually if you take `contact: true` instead of `contact: 'true'` task becomes idempotent

**Comment by Dennis-Q** [comment] 2024-07-26 09:26
Hi @msekania,

Thanks for investigating further. I have tested more myself and indeed, both `true` and `false` make it work as expected!

And while I agree in general a boolean should be a boolean, my experience is that with multiple Ansible modules (not specifically the checkmk ones) the value `'true'` generally works better than `true` in some cases, which is the reason for us to pick the string-variant instead (which I agree is technically not the same).

Still, in my opinion, the module should not accept strings at all, or, accept strings `'true'` and `'false'` but the behavior should be identical as if they are real booleans.


Maybe this is something you still want to improve so other users don't get confused by the behavior? :)

Either way, for us it's fixed now, thank you very much for looking into it.

**Comment by robin-checkmk** [comment] 2024-07-29 15:11
I usually go with the `| bool` filter, to make sure variables are translated into boolean values.
So I think it is perfectly fine, if a module expects proper input. But maybe @msekania still has an idea for improvement?
If not that is fine, this is not a bug, but a convenience issue, I think.

**Comment by robin-checkmk** [comment] 2024-08-01 07:25
Okay, so I am hearing: We have a workaround and a proper fix is not trivial. Correct?

**Comment by msekania** [comment] 2024-08-01 08:06
@robin-checkmk, 

I would not call it workaround. This is how ansible works when one has nested dict-s as an input and structure is not (or might even could not be) completely mapped in module parameter structure. (we do not speak about value_raw here)

It will be a feature request and not a bug fix then.

**Comment by robin-checkmk** [comment] 2024-08-09 06:14
Alright, re-reading the thread I do agree with msekania's perspective.
It might be inconvenient or even puzzling at times, but the module is not inherently broken.
In the foreseeable future, I do not see us investing in a rewrite of the module as mentioned.
If anyone feels like they can contribute, please do open a PR and we can work on improving the module together.
But as of now, I will close this issue, as the bottom line is: Works as designed.

**Closed by robin-checkmk** 2024-08-09 06:14 UTC
Labels: bug, module:folder

**Comment by Dennis-Q** [comment] 2024-08-09 15:16
Fully understood and would have suggested the same. Thank you for debugging and looking into this @msekania  and @robin-checkmk ! Great support
