### ISSUE TITLE
[BUG] Register Linux agent for TLS fails with CRE edition

### ISSUE THREAD

**Issue by MaxiReglisse** [Checkmk/ansible-collection-checkmk.general#553] opened 2024-02-09 10:35 UTC
**Describe the bug**
When deploying a Linux agent, the checkmk.general.agent role fails at the time of the agent's TLS registration.
```
TASK [checkmk.general.agent : Linux: Register Agent for TLS.] 
task path: /usr/local/ansible_collections/checkmk/general/roles/agent/tasks/Linux.yml:119
fatal: [3d.inframshe.univ-fcomte.fr]: FAILED! => {
    "msg": "The conditional check 'checkmk_agent_controller_binary.stat.exists | bool\nand checkmk_agent_tls | bool\nand (checkmk_agent_auth is defined and checkmk_agent_auth | length)\n' failed. The error was: error while evaluating conditional (checkmk_agent_controller_binary.stat.exists | bool\nand checkmk_agent_tls | bool\nand (checkmk_agent_auth is defined and checkmk_agent_auth | length)\n): {% if checkmk_agent_secret is defined and checkmk_agent_secret | length %}{{ checkmk_agent_secret }}{% else %}{{ checkmk_agent_pass }}{% endif %}: 'checkmk_agent_pass' is undefined\n\nThe error appears to be in '/usr/local/ansible_collections/checkmk/general/roles/agent/tasks/Linux.yml': line 119, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"{{ ansible_system }}: Register Agent for TLS.\"  # noqa no-changed-when\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}
```

**Component Name**
Component Name: checkmk/general/roles/agent/tasks/Linux.yml:119

**Ansible Version**
```console
ansible [core 2.12.9]
```

**Checkmk Version and Edition**
```console
CRE
check-mk-agent          2.0.0p5-1
check-mk-raw-2.0.0p5    0.buster
```

**Collection Version**
```console
community.general        4.2.0
```

**To Reproduce**
Simply call up the role in a playbook, after declaring the necessary variables.
```
  roles:
    - role: checkmk.general.agent
```

**Expected behavior**
This bug occurs with the CRE edition of checkmk. 
In the old version of the collection, tribe29.checkmk 0.9.0, tests were carried out to check which edition was being used.

More precisely, in tribe29/checkmk/roles/agent/tasks/main.yml, we had this:
```
- name: "Register Agent for TLS using Automation Secret."
...
  when: |
    (checkmk_agent_edition == "cee" or checkmk_agent_edition == "cfe")
    and checkmk_agent_controller_binary.stat.exists | bool
    and checkmk_agent_tls | bool
    and (checkmk_agent_pass is defined and checkmk_agent_pass | length)
    and (checkmk_agent_secret is not defined)
```

**Actual behavior**
In the current version, editing (CRE, CEE, CCE, CME) is not verified in checkmk/general/roles/agent/tasks/Linux.yml... The password is not set either, the task fails.
```
- name: "{{ ansible_system }}: Register Agent for TLS."  # noqa no-changed-when
...
  when: |
    checkmk_agent_controller_binary.stat.exists | bool
    and checkmk_agent_tls | bool
    and (checkmk_agent_auth is defined and checkmk_agent_auth | length)
```

**Minimum reproduction example**
Here's the playbook I use:
```
- name: "Déploiement d'un agent Checkmk"

  hosts: "{{ target }}"

  collections:
    - checkmk.general

  vars:
    - checkmk_agent_edition: "cre"
    - checkmk_agent_server: "checkmk.inframshe.univ-fcomte.fr"
    - checkmk_agent_site: "mshe"
    - checkmk_agent_version: "2.0.0p5"
    - checkmk_host_server_url: "http://checkmk.inframshe.univ-fcomte.fr/"
    - checkmk_host_automation_user: "automation"
    - checkmk_host_automation_secret: "f6...be"
    - checkmk_host_folder: "/"
    - checkmk_host_state: "present"
    - checkmk_agent_no_log: True
    - checkmk_agent_tls: False

  tasks:
    - name: Configure un agent checkmk (un hôte client)
      checkmk.general.host:
        server_url:        "{{ checkmk_host_server_url }}"
        site:              "{{ checkmk_agent_site }}"
        automation_user:   "{{ checkmk_host_automation_user }}"
        automation_secret: "{{ checkmk_host_automation_secret }}"
        name:              "{{ inventory_hostname }}"
        attributes:
            site:          "{{ checkmk_agent_site }}"
        folder:            "{{ checkmk_host_folder }}"
        state:             "{{ checkmk_host_state }}"

  roles:
    - role: checkmk.general.agent
```

Thank you in advance for your attention

Ernest

**Comment by robin-checkmk** [comment] 2024-02-09 18:48
Hi @MaxiReglisse and thanks for reporting this issue!

A few things up front:
1. Your Checkmk version is ancient and while we try to be as backwards compatible with this collection, we cannot guarantee it. You definitely want to upgrade your Checkmk.
2. The removed checks for the edition, which you mentioned, were removed as they were unnecessary due to restructuring the role, if I recall that correctly. They should not have any impact on your situation.
3. Your Ansible installation is also rather old.
4. The error message you are getting does not line up with our tests, the task is fine. You might want to check, if the role was somehow modified on your end.

Please take care of the above points and report back, if the issue is still there. Thanks!

**Comment by MaxiReglisse** [comment] 2024-02-18 17:55
Thanks Robin!

I updated the version of my checkmk server to 2.2.0p22. But the problem was exactly the same... In desperation, I updated the version of Ansible on my deployment server (Ubuntu 22.04) from 2.12.9 to 2.15.9, and miraculously (!), the playbook ran correctly!

Needless to say, I don't understand why the Ansible update corrected the execution of my checkmk_agent.yml playbook... I was still using version 2.12.9 regularly this week on numerous playbooks without encountering any particular difficulties.

Anyway, thanks for inviting me to perform these two updates.

**Comment by robin-checkmk** [comment] 2024-02-19 18:51
The error message complained about syntax, so either there was a bug in your version, or we were using a construct, that does not work in that version. As you can see in [SUPPORT.md](https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/SUPPORT.md), we do not support this EOL Ansible version for quite some time, which means, we also do not test against it anymore. So to me, it sounds sensible that an update of Ansible helped.

One way or another, the important thing is, that you could solve the issue. :)

So I will close this ticket accordingly.

**Closed by robin-checkmk** 2024-02-19 18:51 UTC
Labels: bug, invalid, needs-info, role:agent
