### ISSUE TITLE
[BUG] Crash using host module on RHEL7

### ISSUE THREAD

**Issue by racke** [Checkmk/ansible-collection-checkmk.general#652] opened 2024-08-16 13:20 UTC
**Describe the bug**
Host module crashes on RHEL7 when registering a host. Other distributions (SLES, Ubuntu, RHEL 8/9) are not affected. 
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: super() takes at least 1 argument (0 given)
fatal: [xxx]: FAILED! => changed=false
  module_stderr: |-
    Shared connection to 10.95.8.147 closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1723800346.0910168-5689-254751096199345/AnsiballZ_host.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1723800346.0910168-5689-254751096199345/AnsiballZ_host.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1723800346.0910168-5689-254751096199345/AnsiballZ_host.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.checkmk.general.plugins.modules.host', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
        fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_checkmk.general.host_payload_o0jjBC/ansible_checkmk.general.host_payload.zip/ansible_collections/checkmk/general/plugins/modules/host.py", line 887, in <module>
      File "/tmp/ansible_checkmk.general.host_payload_o0jjBC/ansible_checkmk.general.host_payload.zip/ansible_collections/checkmk/general/plugins/modules/host.py", line 883, in main
      File "/tmp/ansible_checkmk.general.host_payload_o0jjBC/ansible_checkmk.general.host_payload.zip/ansible_collections/checkmk/general/plugins/modules/host.py", line 856, in run_module
      File "/tmp/ansible_checkmk.general.host_payload_o0jjBC/ansible_checkmk.general.host_payload.zip/ansible_collections/checkmk/general/plugins/modules/host.py", line 295, in __init__
    TypeError: super() takes at least 1 argument (0 given)
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
```

**Component Name**

Component Name: [checkmk.general.host](https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/plugins/modules/host.py)

**Ansible Version**

```console
$ ansible --version
 2.9.21
```

**Checkmk Version and Edition**

```console
2.3.0p9 CME
```

**Collection Version**

```console
5.1.0 
```

**Expected behavior**

No crash.

**Actual behavior**

Crash

**Minimum reproduction example**

```yaml

```

**Additional context**

**Comment by robin-checkmk** [comment] 2024-08-16 13:22
@racke your Ansible is way out of date. Like more than two years EOL: https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix

Please update to a supported Ansible version, then I am positive the crash will go away.

**Comment by racke** [comment] 2024-08-19 12:54
I upgraded Python and Ansible:

ansible [core 2.15.12]
python version = 3.9.19 (main, Aug 19 2024, 12:55:12) [GCC 7.5.0] 

Still crashes:

```
TASK [xxx : Register hosts] ********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: super() takes at least 1 argument (0 given)
fatal: [xxx]: FAILED! => changed=false
  module_stderr: |-
    Shared connection to 10.95.8.179 closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1724067522.4349155-3555-10331587637/AnsiballZ_host.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1724067522.4349155-3555-10331587637/AnsiballZ_host.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1724067522.4349155-3555-10331587637/AnsiballZ_host.py", line 48, in invoke_module
        run_name='__main__', alter_sys=True)
      File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
        fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_checkmk.general.host_payload_0ESx6s/ansible_checkmk.general.host_payload.zip/ansible_collections/checkmk/general/plugins/modules/host.py", line 887, in <module>
      File "/tmp/ansible_checkmk.general.host_payload_0ESx6s/ansible_checkmk.general.host_payload.zip/ansible_collections/checkmk/general/plugins/modules/host.py", line 883, in main
      File "/tmp/ansible_checkmk.general.host_payload_0ESx6s/ansible_checkmk.general.host_payload.zip/ansible_collections/checkmk/general/plugins/modules/host.py", line 856, in run_module
      File "/tmp/ansible_checkmk.general.host_payload_0ESx6s/ansible_checkmk.general.host_payload.zip/ansible_collections/checkmk/general/plugins/modules/host.py", line 295, in __init__
    TypeError: super() takes at least 1 argument (0 given)
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error

```

**Comment by robin-checkmk** [comment] 2024-08-20 11:02
Did you also update Python on the controlled node (not the controller), where the module is actually executed?

**Comment by racke** [comment] 2024-08-20 13:57
No, but according to the matrix 2.7 is fine for Ansible 2.15. I will check if an upgrade is possible.

**Comment by racke** [comment] 2024-08-20 14:06
I think it is possible to install Python3 alongside Python2 and use the first only for Ansible.

**Comment by racke** [comment] 2024-08-20 14:36
I found a SLES12 machine that crashes as well, so missing support of Python 2.7 is very likely the culprit.

**Comment by racke** [comment] 2024-08-22 06:50
Problem is solved, but it would be good to document the Python3 requirement.

**Comment by robin-checkmk** [comment] 2024-08-22 10:34
Thanks for the research, and I am glad the issue is fixed on your end!
I just realized, that I got confused at some point, as I thought you were doing something different.
But in this kind of scenario, you could also delegate the registration of the host to a host with up-to-date Python.

Also, as Ansible 2.15 is reaching EOL in November, after it already does not receive any security updates anymore, I will not put a hint in the documentation, as it would be obsolete within a few months. I think this issue should be documentation enough.

**Closed by robin-checkmk** 2024-08-22 10:34 UTC
Labels: bug, invalid
