### ISSUE TITLE
[BUG] "Activate changes" triggered by "Ensure registration readyness" still does not work for us

### ISSUE THREAD

**Issue by p088gll** [Checkmk/ansible-collection-checkmk.general#501] opened 2023-12-16 15:49 UTC
**Describe the bug**
We have a distrubted environment and are using an agent playbook to add hosts automatically to the monitoring system.
Hosts are created correctly on the main site and get the right remote monitoring site configured.
The next step would be to activate such a  change to move the new host to its monitoring site. 
This happens with the agent role in Linux.yml.  When checkmk_agent_create_result.changed is true handlers are flushed the the "Activate Changes" handler is executed.

The problem we are facing can be seen in the following error:

```
RUNNING HANDLER [checkmk.general.agent : Activate Changes.] ********************
task path: /home/golla/git/ansible-runner/project/collections/ansible_collections/checkmk/general/roles/agent/handlers/main.yml:2
[...]
fatal: [ns.pop1.xyz.de -> monitoring.noc.xyz.de(192.168.100.7)]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "automation_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "automation_user": "registration",
            "force_foreign_changes": true,
            "redirect": true,
            "server_url": "https://monitoring.noc.xyz.de:443/",
            "site": "noc",
            "sites": [],
            "validate_certs": true
        }
    },
    "msg": "400 - Bad request: Parameter or validation failure Details: b'<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\\n<html><head>\\n<title>400 Bad Request</title>\\n</head><body>\\n<h1>Bad Request</h1>\\n<p>Your browsersent a request that this server could not understand.<br />\\nReason: You\\'re speaking plain HTTP to an SSL-enabled server port.<br />\\n Instead use the HTTPS scheme to access this URL, please.<br />\\n</p>\\n</body></html>\\n'"
}
```
As can be seen, the error message is that ansible is trying to connect in PLAIN HTTP to an SSL-enabled server port, however this is not true since the server_url is https and the port is 443 and this port is SSL-enabled as can be seen with openssl s_client

**Component Name**
Component Name: activation

**Ansible Version**
```console
$ ansible --version
ansible [core 2.15.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/golla/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/golla/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

**Checkmk Version and Edition**

```console
2.2.0p14.cre
```

**Collection Version**

```console
$ ansible-galaxy collection list
# /home/golla/.ansible/collections/ansible_collections
Collection                    Version
----------------------------- -------
checkmk.general               4.0.1
```

**To Reproduce**
1. Remove Hosts
2. Run Playbook like this one
```console
 ....
  tasks:
    - name: include checkmk agent role
      import_role:
        name: checkmk.general.agent
```

6. See error

**Expected behavior**
clearly and concisely there  should be no error.

**Actual behavior**
Error as described

**Additional Information**
Tracing the error further into 

- plugins/module_utils/api.py

the error could also be in the interpretation of redirects of the fetch_url function. When I do a curl I am naturally getting the following
```console
$ curl https://monitoring.noc.xyz.de/noc
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://127.0.0.1:5000/noc/check_mk/">here</a>.</p>
```
but I am not sure if I am on the right track here, because:

I should also mention that calling checkmk.general.activation directly (not with a handler) is **always** working - which is also my workaround.

**Comment by robin-checkmk** [comment] 2023-12-18 12:47
I am fairly certain, that this is related to this: https://github.com/Checkmk/ansible-collection-checkmk.general/issues/414#issuecomment-1808146955
@lgetwan FYI.

**Comment by lgetwan** [comment] 2023-12-19 09:38
That's true, @robin-checkmk.

**Comment by robin-checkmk** [comment] 2023-12-19 09:41
Closing this as a duplicate of #414.
@p088gll please subscribe to the aforementioned issue, to be aware of possible fixes.

**Closed by robin-checkmk** 2023-12-19 09:41 UTC
Labels: bug, module:activation
